### ISSUE TITLE
walking group finished successfully after 5 minutes

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#266]
```
28/05/2015 14:02:42 16 [TASK_SUCCEEDED]     367 walking_group_slow  WalkingGruppeStart  28/05/2015 13:57:26 28/05/2015 13:57:26 28/05/2015 14:57:26 100
28/05/2015 14:02:42 9 [EXECUTION_SUCCEEDED]     367 walking_group_slow  WalkingGruppeStart  28/05/2015 13:57:26 28/05/2015 13:57:26 28/05/2015 14:57:26 100
28/05/2015 13:57:42 8 [EXECUTION_STARTED]       367 walking_group_slow  WalkingGruppeStart  28/05/2015 13:57:26 28/05/2015 13:57:26 28/05/2015 14:57:26 100
28/05/2015 13:57:42 5 [NAVIGATION_SUCCEEDED]        367 walking_group_slow  WalkingGruppeStart  28/05/2015 13:57:26 28/05/2015 13:57:26 28/05/2015 14:57:26 100
28/05/2015 13:57:22 4 [NAVIGATION_STARTED]      367 walking_group_slow  WalkingGruppeStart  28/05/2015 13:57:26 28/05/2015 13:57:26 28/05/2015 14:57:26 100
28/05/2015 13:57:21 3 [TASK_STARTED]        367 walking_group_slow  WalkingGruppeStart  28/05/2015 13:57:26 28/05/2015 13:57:26 28/05/2015 14:57:26 100
28/05/2015 13:56:57 1 [ADDED]
```

The scheduler decided or got notified that the task was successful (for whatever reason) after exactly 5 minutes. @cdondrup any idea? I manually triggered it via the axclient and it worked again. The staff at HdB say they might have pressed the wrong button.

This task had been an on demand task via the web gui as below:

```
start_node_id: WalkingGruppeStart
end_node_id: WalkingGruppeStart
action: walking_group_slow
start_after: 
  secs: 1432817846
  nsecs: 115170955
end_before: 
  secs: 1432821446
  nsecs: 115170955
max_duration: 
  secs: 3600
  nsecs: 0
execution_time: 
  secs: 0
  nsecs: 0
priority: 100
```
