### ISSUE TITLE
Calendar Task Droped

### ISSUE THREAD

**Issue by Jailander** [strands-project/aaf_deployment#382]
Hi a calendar Task was dropped giving this reason it was added ten minutes in advance
```bash
[INFO] [WallTime: 1480072020.056562] Dropping time-critical task n287__info_task_server_at_Rezeption as -418.473938065 not enough time for execution
```
full log here:
[calendar-log.txt](https://github.com/strands-project/aaf_deployment/files/613121/calendar-log.txt)
Line 1628 for previous message

**Comment by marc-hanheide** [comment]
@jailander can you tell me what time the task was supposed to start and at what time you added it? 

@hawesie, what does a negative time mean here:
```
[INFO] [WallTime: 1480072020.055082] Expected navigation time fo
r time-critical task: 598
[INFO] [WallTime: 1480072020.056562] Dropping time-critical task
 n287__info_task_server_at_Rezeption as -418.473938065 not enoug
h time for execution
```

and is this in seconds?

**Comment by Jailander** [comment]
I added it at 11:02 GMT it was to start at 11:10 GMT

**Comment by Jailander** [comment]
too short notice?

**Comment by marc-hanheide** [comment]
no, that should be alright...

**Comment by hawesie** [comment]
It looks at travel time, which is 598 seconds, and it checks it has enough time to travel to the task location to execute it. The check was done at 1480072020.055082 which is 11:07. It therefore thinks it would be 2 minutes late for the task so I think this is why it was dropped. Have you got `allowed_lateness` set to 0 locally?

**Comment by hawesie** [comment]
Oops, ignore that.

**Comment by hawesie** [comment]
(because if it was set to 300 then it shouldn't have been dropped)

**Comment by hawesie** [comment]
Just for reference: https://github.com/strands-project/strands_executive/blob/indigo-devel/task_executor/scripts/mdp_task_executor.py#L457

**Comment by marc-hanheide** [comment]
It thinks it'll be 10 minutes (~600 seconds) travel time. Then it was submitted too late. Actually, the calendar only ever presents tasks to the scheduler 15 before the are due, with such long travel times that's problematic. We never really have 10 minutes travel time in the environment. Where does that come from? @jailander can you check the predictions.

**Comment by hawesie** [comment]
(oops, my bad maths!)

**Comment by hawesie** [comment]
The travel time comes from the expected time to complete navigation given by the MDP, but we scale it a bit because the MDP underestimates the travel time as it also includes the effects of potential failures.

https://github.com/strands-project/strands_executive/blob/indigo-devel/task_executor/scripts/mdp_task_executor.py#L694

**Comment by marc-hanheide** [comment]
Wow, that formula looks dangerous... So, a probability of 0.1 is causing an overestimate of 10 times the predicted time??? That probably causes many of our tasks to be dropped. @jailander can you tell me what the probabilities and estimated travel times are for the edges? Also, @hawesie, how is that probability computed from the individual edge probabilities?

**Comment by Jailander** [comment]
Hi sorry missed this, what do you mean the formula for the probabilites or do you want me to query what the probablities and times where at that time?

**Comment by marc-hanheide** [comment]
Just curious what our current estimates are for probabilities and times. So I meant the query.

**Comment by Jailander** [comment]
Yes I thought so
```YAML
edge_ids: ['Ambulanz_WayPoint67', 'Ambulanz_WayPoint4', 'Cafeteria_WayPoint26', 'Cafeteria_WayPoint49', 'ChargingPoint_Station', 'Eingang_WayPoint2', 'Eingang_WayPoint86', 'Eingang_WayPoint90', 'Feuerloescher_WayPoint85', 'Feuerloescher_Seminarraum', 'Frisoer_WayPoint26', 'Frisoer_WayPoint35', 'Frisoer_WayPoint17', 'Kapelle_WayPoint14', 'Kapelle_WayPoint76', 'Kindergarten_WayPoint88', 'Konferenzraum_WayPoint62', 'Konferenzraum_WayPoint63', 'Lift1_WayPoint58', 'Lift1_Teekueche', 'Lift1_WayPoint76', 'Lift1_WayPoint34', 'Lift2_WayPoint50', 'Lift2_WayPoint111', 'Lift3_WayPoint4', 'Lift3_WayPoint89', 'Rezeption_WayPoint86', 'Rezeption_WayPoint91', 'Seminarraum_Feuerloescher', 'Seminarraum_WayPoint39', 'Seminarraum_WayPoint85', 'Station_ChargingPoint', 'Station_WayPoint2', 'Station_WayPoint91', 'Teekueche_Lift1', 'Teekueche_WayPoint34', 'WayPoint11_WayPoint20', 'WayPoint11_WayPoint64', 'WayPoint111_Lift2', 'WayPoint111_WayPoint7', 'WayPoint12_WayPoint7', 'WayPoint12_WayPoint66', 'WayPoint1
 3_WayPoint65', 'WayPoint13_WayPoint68', 'WayPoint13_WayPoint88', 'WayPoint14_WayPoint51', 'WayPoint14_WayPoint76', 'WayPoint14_Kapelle', 'WayPoint15_WayPoint4', 'WayPoint15_WayPoint67', 'WayPoint15_WayPoint89', 'WayPoint17_WayPoint26', 'WayPoint17_WayPoint35', 'WayPoint17_Frisoer', 'WayPoint17_WayPoint90', 'WayPoint19_WayPoint7', 'WayPoint19_WayPoint21', 'WayPoint2_Station', 'WayPoint2_Eingang', 'WayPoint2_WayPoint86', 'WayPoint2_WayPoint91', 'WayPoint20_WayPoint11', 'WayPoint20_WayPoint65', 'WayPoint21_WayPoint19', 'WayPoint21_WayPoint28', 'WayPoint26_Cafeteria', 'WayPoint26_WayPoint17', 'WayPoint26_Frisoer', 'WayPoint26_WayPoint90', 'WayPoint28_WayPoint21', 'WayPoint28_WayPoint85', 'WayPoint32_WayPoint58', 'WayPoint32_WayPoint59', 'WayPoint32_WayPoint82', 'WayPoint34_WayPoint48', 'WayPoint34_Teekueche', 'WayPoint34_Lift1', 'WayPoint35_WayPoint17', 'WayPoint35_Frisoer', 'WayPoint35_WayPoint90', 'WayPoint39_WayPoint63', 'WayPoint39_Seminarraum', 'WayPoint4_Lift3', 'WayPoint4_WayPoin
 t15', 'WayPoint4_Ambulanz', 'WayPoint4_WayPoint89', 'WayPoint4_WayPoint80', 'WayPoint43_WayPoint47', 'WayPoint43_WayPoint60', 'WayPoint43_WayPoint59', 'WayPoint45_WayPoint54', 'WayPoint45_WayPoint82', 'WayPoint47_WayPoint43', 'WayPoint47_WayPoint57', 'WayPoint47_WayPoint83', 'WayPoint48_WayPoint34', 'WayPoint48_WayPoint53', 'WayPoint49_WayPoint50', 'WayPoint49_Cafeteria', 'WayPoint50_WayPoint49', 'WayPoint50_Lift2', 'WayPoint51_WayPoint14', 'WayPoint51_WayPoint66', 'WayPoint53_WayPoint48', 'WayPoint53_WayPoint82', 'WayPoint54_WayPoint45', 'WayPoint54_WayPoint55', 'WayPoint55_WayPoint54', 'WayPoint55_WayPoint56', 'WayPoint56_WayPoint55', 'WayPoint56_WayPoint83', 'WayPoint57_WayPoint47', 'WayPoint58_WayPoint32', 'WayPoint58_Lift1', 'WayPoint59_WayPoint32', 'WayPoint59_WayPoint43', 'WayPoint60_WayPoint43', 'WayPoint60_WayPoint84', 'WayPoint61_WayPoint62', 'WayPoint61_WayPoint84', 'WayPoint62_Konferenzraum', 'WayPoint62_WayPoint61', 'WayPoint63_WayPoint39', 'WayPoint63_Konferenzraum', '
 WayPoint64_WayPoint11', 'WayPoint64_WayPoint80', 'WayPoint65_WayPoint13', 'WayPoint65_WayPoint20', 'WayPoint66_WayPoint12', 'WayPoint66_WayPoint7', 'WayPoint66_WayPoint51', 'WayPoint67_WayPoint15', 'WayPoint67_Ambulanz', 'WayPoint68_WayPoint13', 'WayPoint68_WayPoint88', 'WayPoint7_WayPoint12', 'WayPoint7_WayPoint19', 'WayPoint7_WayPoint66', 'WayPoint7_WayPoint111', 'WayPoint76_WayPoint14', 'WayPoint76_Lift1', 'WayPoint76_Kapelle', 'WayPoint8_WayPoint87', 'WayPoint8_WayPoint91', 'WayPoint80_WayPoint64', 'WayPoint80_Lift3', 'WayPoint80_WayPoint4', 'WayPoint80_WayPoint89', 'WayPoint81_WayPoint86', 'WayPoint81_WayPoint90', 'WayPoint82_WayPoint45', 'WayPoint82_WayPoint53', 'WayPoint82_WayPoint32', 'WayPoint83_WayPoint56', 'WayPoint83_WayPoint47', 'WayPoint84_WayPoint61', 'WayPoint84_WayPoint60', 'WayPoint85_Feuerloescher', 'WayPoint85_WayPoint28', 'WayPoint85_Seminarraum', 'WayPoint86_Rezeption', 'WayPoint86_WayPoint81', 'WayPoint86_WayPoint2', 'WayPoint86_Eingang', 'WayPoint86_WayPoint9
 0', 'WayPoint86_WayPoint91', 'WayPoint87_WayPoint8', 'WayPoint87_WayPoint89', 'WayPoint87_WayPoint91', 'WayPoint88_WayPoint68', 'WayPoint88_Kindergarten', 'WayPoint88_WayPoint13', 'WayPoint89_Lift3', 'WayPoint89_WayPoint15', 'WayPoint89_WayPoint4', 'WayPoint89_WayPoint87', 'WayPoint89_WayPoint80', 'WayPoint90_WayPoint35', 'WayPoint90_WayPoint17', 'WayPoint90_Eingang', 'WayPoint90_WayPoint81', 'WayPoint90_WayPoint26', 'WayPoint90_WayPoint86', 'WayPoint91_WayPoint8', 'WayPoint91_Station', 'WayPoint91_WayPoint2', 'WayPoint91_WayPoint86', 'WayPoint91_WayPoint87', 'WayPoint91_Rezeption', 'Ambulanz_WayPoint9', 'Ambulanz_WayPoint3', 'Lift3_WayPoint80', 'WalkingGruppeStart_WayPoint42', 'WalkingGruppeStart_WayPoint46', 'WayPoint16_WayPoint18', 'WayPoint16_WayPoint25', 'WayPoint18_WayPoint16', 'WayPoint25_WayPoint9', 'WayPoint25_WayPoint16', 'WayPoint3_WayPoint9', 'WayPoint3_WayPoint67', 'WayPoint3_Ambulanz', 'WayPoint31_WayPoint42', 'WayPoint31_WayPoint88', 'WayPoint34_WayPoint52', 'WayPoint
 42_WayPoint31', 'WayPoint42_WalkingGruppeStart', 'WayPoint42_WayPoint46', 'WayPoint44_WayPoint46', 'WayPoint46_WalkingGruppeStart', 'WayPoint46_WayPoint44', 'WayPoint46_WayPoint42', 'WayPoint52_WayPoint34', 'WayPoint67_WayPoint3', 'WayPoint67_WayPoint9', 'WayPoint88_WayPoint31', 'WayPoint9_WayPoint3', 'WayPoint9_WayPoint25', 'WayPoint9_WayPoint67', 'WayPoint9_Ambulanz']
probs: [1.0, 1.0, 0.8999999761581421, 0.9666666388511658, 0.01, 0.75, 0.95652174949646, 0.8666666746139526, 0.75, 1.0, 0.6000000238418579, 0.375, 1.0, 1.0, 1.0, 0.07692307978868484, 1.0, 0.8333333134651184, 0.6190476417541504, 0.01, 0.8125, 1.0, 0.30123046040534973, 0.045320477336645126, 0.20000000298023224, 0.01, 0.625, 1.0, 0.01, 1.0, 0.8571428656578064, 0.1803278625011444, 0.7121211886405945, 0.013888888992369175, 0.01, 0.75, 0.6875, 0.8461538553237915, 0.7021276354789734, 0.931034505367279, 0.800000011920929, 0.9090909361839294, 1.0, 0.1428571492433548, 0.8333333134651184, 1.0, 0.9166666865348816, 1.0, 0.3333333432674408, 1.0, 0.03205128386616707, 0.9545454382896423, 0.1111111119389534, 0.01, 0.9607843160629272, 0.8181818127632141, 1.0, 0.21621622145175934, 0.9333333373069763, 0.13333334028720856, 0.8709677457809448, 1.0, 1.0, 0.8999999761581421, 1.0, 0.01, 0.9444444179534912, 0.1428571492433548, 0.699999988079071, 1.0, 1.0, 1.0, 1.0, 0.8888888955116272, 0.8571428656578064, 0.066
 66667014360428, 1.0, 0.01, 0.9471713900566101, 0.08227848261594772, 1.0, 0.8333333134651184, 0.3333333432674408, 0.2857142984867096, 1.0, 0.6666666865348816, 0.20000000298023224, 0.9230769276618958, 1.0, 0.75, 0.8888888955116272, 1.0, 1.0, 0.25, 1.0, 0.8571428656578064, 1.0, 0.9666666388511658, 0.8787878751754761, 0.8888888955116272, 1.0, 1.0, 0.9772727489471436, 1.0, 1.0, 1.0, 0.8888888955116272, 1.0, 0.8888888955116272, 0.9444444179534912, 0.8999999761581421, 0.9444444179534912, 0.9375, 1.0, 1.0, 0.9166666865348816, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9090909361839294, 0.01, 0.849056601524353, 1.0, 0.01, 1.0, 0.7142857313156128, 1.0, 0.1764705926179886, 0.8333333134651184, 0.9555555582046509, 0.8888888955116272, 0.8888888955116272, 0.9375, 1.0, 1.0, 0.06756756454706192, 1.0, 1.0, 0.01, 0.8888888955116272, 0.8125, 0.5051546096801758, 0.8888888955116272, 1.0, 1.0, 1.0, 0.8999999761581421, 1.0, 1.0, 0.25, 1.0, 1.0, 0.75, 0.8703703880310059, 0.9142857193946838, 1.
 0, 0.0476190485060215, 0.9166666865348816, 0.3076923191547394, 0.05343511328101158, 0.4669376611709595, 0.01, 0.6666666865348816, 0.08571428805589676, 0.01, 0.25, 0.4444444477558136, 0.6055191159248352, 0.017686782404780388, 0.09375, 0.9318181872367859, 0.25, 0.9333333373069763, 0.800000011920929, 0.841269850730896, 0.04545454680919647, 0.0416666679084301, 0.8333333134651184, 0.8780487775802612, 0.8055555820465088, 0.6666666865348816, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
durations:
  -
    secs: 13
    nsecs: 837605676
  -
    secs: 8
    nsecs: 638386170
  -
    secs: 5
    nsecs: 264245009
  -
    secs: 7
    nsecs: 727455363
  -
    secs: 24
    nsecs: 569758604
  -
    secs: 11
    nsecs: 967913501
  -
    secs: 9
    nsecs: 291504358
  -
    secs: 16
    nsecs: 223720860
  -
    secs: 6
    nsecs: 858135365
  -
    secs: 9
    nsecs: 818879015
  -
    secs: 5
    nsecs: 714486653
  -
    secs: 9
    nsecs: 200940586
  -
    secs: 8
    nsecs: 519018609
  -
    secs: 3
    nsecs: 152799800
  -
    secs: 7
    nsecs: 912026985
  -
    secs: 8
    nsecs: 773552755
  -
    secs: 12
    nsecs: 870344466
  -
    secs: 16
    nsecs: 503376782
  -
    secs: 20
    nsecs: 604419435
  -
    secs: 19
    nsecs: 427507501
  -
    secs: 11
    nsecs: 983864297
  -
    secs: 12
    nsecs: 907461311
  -
    secs: 7
    nsecs: 521753525
  -
    secs: 4
    nsecs: 752550001
  -
    secs: 8
    nsecs: 604828884
  -
    secs: 16
    nsecs: 138449804
  -
    secs: 9
    nsecs:  42336895
  -
    secs: 12
    nsecs: 309191500
  -
    secs: 4
    nsecs: 983227342
  -
    secs: 13
    nsecs: 270122005
  -
    secs: 10
    nsecs: 471706128
  -
    secs: 32
    nsecs: 736073840
  -
    secs: 2
    nsecs: 781986931
  -
    secs: 6
    nsecs: 160166052
  -
    secs: 13
    nsecs:  52420105
  -
    secs: 5
    nsecs: 443548204
  -
    secs: 12
    nsecs: 243888664
  -
    secs: 7
    nsecs: 404473797
  -
    secs: 4
    nsecs: 359698823
  -
    secs: 6
    nsecs: 529118684
  -
    secs: 7
    nsecs:  72929787
  -
    secs: 8
    nsecs: 398002032
  -
    secs: 6
    nsecs: 778794162
  -
    secs: 13
    nsecs: 141503948
  -
    secs: 16
    nsecs: 229074734
  -
    secs: 11
    nsecs: 106594137
  -
    secs: 11
    nsecs: 352389284
  -
    secs: 5
    nsecs: 575950468
  -
    secs: 24
    nsecs: 906780563
  -
    secs: 17
    nsecs: 786443996
  -
    secs: 7
    nsecs: 493426054
  -
    secs: 7
    nsecs: 535101482
  -
    secs: 35
    nsecs: 890209074
  -
    secs: 5
    nsecs: 924586088
  -
    secs: 7
    nsecs: 814608493
  -
    secs: 13
    nsecs:  37633985
  -
    secs: 10
    nsecs: 960726560
  -
    secs: 12
    nsecs: 411100971
  -
    secs: 11
    nsecs: 448091530
  -
    secs: 9
    nsecs: 306017616
  -
    secs: 9
    nsecs:  51500419
  -
    secs: 12
    nsecs: 463923825
  -
    secs: 10
    nsecs: 409173860
  -
    secs: 12
    nsecs: 280258466
  -
    secs: 11
    nsecs:  82720121
  -
    secs: 6
    nsecs: 139379169
  -
    secs: 9
    nsecs:    271064
  -
    secs: 7
    nsecs: 566551789
  -
    secs: 18
    nsecs:  82709166
  -
    secs: 12
    nsecs: 985848490
  -
    secs: 5
    nsecs: 887310451
  -
    secs: 7
    nsecs: 619515781
  -
    secs: 7
    nsecs: 626181147
  -
    secs: 11
    nsecs: 270367819
  -
    secs: 12
    nsecs: 704935925
  -
    secs: 36
    nsecs: 385954592
  -
    secs: 11
    nsecs: 596092897
  -
    secs: 8
    nsecs: 151057929
  -
    secs: 12
    nsecs: 642598729
  -
    secs: 8
    nsecs:  93639352
  -
    secs: 11
    nsecs: 555341986
  -
    secs: 13
    nsecs: 615968728
  -
    secs: 18
    nsecs: 581107380
  -
    secs: 10
    nsecs:  86766109
  -
    secs: 10
    nsecs: 378235747
  -
    secs: 9
    nsecs: 831598573
  -
    secs: 11
    nsecs: 592975915
  -
    secs: 9
    nsecs: 985130170
  -
    secs: 6
    nsecs: 914510636
  -
    secs: 22
    nsecs: 787831023
  -
    secs: 5
    nsecs: 343481657
  -
    secs: 5
    nsecs: 311062797
  -
    secs: 9
    nsecs: 724840115
  -
    secs: 10
    nsecs: 571779112
  -
    secs: 4
    nsecs: 972696796
  -
    secs: 13
    nsecs:  70918828
  -
    secs: 9
    nsecs: 510109248
  -
    secs: 7
    nsecs: 637232776
  -
    secs: 8
    nsecs: 979506889
  -
    secs: 8
    nsecs: 136863906
  -
    secs: 7
    nsecs: 523383479
  -
    secs: 10
    nsecs: 418123640
  -
    secs: 19
    nsecs: 297579537
  -
    secs: 10
    nsecs: 352489304
  -
    secs: 5
    nsecs: 709845739
  -
    secs: 5
    nsecs: 108401858
  -
    secs: 5
    nsecs: 491287458
  -
    secs: 5
    nsecs: 216579775
  -
    secs: 6
    nsecs:  35685328
  -
    secs: 5
    nsecs: 613244386
  -
    secs: 6
    nsecs: 401938770
  -
    secs: 8
    nsecs: 179328867
  -
    secs: 7
    nsecs: 940646474
  -
    secs: 17
    nsecs: 170154125
  -
    secs: 7
    nsecs: 409942097
  -
    secs: 26
    nsecs: 419858895
  -
    secs: 7
    nsecs: 270427664
  -
    secs: 4
    nsecs: 711770839
  -
    secs: 13
    nsecs:  72038397
  -
    secs: 6
    nsecs: 448955006
  -
    secs: 13
    nsecs:  59849380
  -
    secs: 13
    nsecs:  80677168
  -
    secs: 10
    nsecs: 612107814
  -
    secs: 16
    nsecs: 232966556
  -
    secs: 7
    nsecs: 117099692
  -
    secs: 11
    nsecs: 796801124
  -
    secs: 11
    nsecs: 117871261
  -
    secs: 8
    nsecs:  21431217
  -
    secs: 6
    nsecs: 323068505
  -
    secs: 10
    nsecs: 379496220
  -
    secs: 20
    nsecs: 715481112
  -
    secs: 16
    nsecs: 944217896
  -
    secs: 15
    nsecs: 115407977
  -
    secs: 9
    nsecs: 328834146
  -
    secs: 11
    nsecs: 772913395
  -
    secs: 11
    nsecs: 414271046
  -
    secs: 18
    nsecs: 261069095
  -
    secs: 6
    nsecs: 846231748
  -
    secs: 8
    nsecs: 121151808
  -
    secs: 12
    nsecs:  61301246
  -
    secs: 10
    nsecs: 770792177
  -
    secs: 10
    nsecs: 330473087
  -
    secs: 6
    nsecs: 191526383
  -
    secs: 7
    nsecs: 384889574
  -
    secs: 13
    nsecs: 275286727
  -
    secs: 9
    nsecs: 450160558
  -
    secs: 14
    nsecs: 496017819
  -
    secs: 21
    nsecs: 851877484
  -
    secs: 9
    nsecs: 842923793
  -
    secs: 7
    nsecs: 272884300
  -
    secs: 6
    nsecs: 713482624
  -
    secs: 5
    nsecs: 147604098
  -
    secs: 7
    nsecs: 555058562
  -
    secs: 6
    nsecs: 663871157
  -
    secs: 5
    nsecs: 174476367
  -
    secs: 7
    nsecs: 476599495
  -
    secs: 4
    nsecs: 698581037
  -
    secs: 12
    nsecs: 860149115
  -
    secs: 9
    nsecs: 417535589
  -
    secs: 9
    nsecs:    334912
  -
    secs: 7
    nsecs: 472914244
  -
    secs: 10
    nsecs: 424989715
  -
    secs: 12
    nsecs: 235338723
  -
    secs: 8
    nsecs: 643184157
  -
    secs: 8
    nsecs:  61627719
  -
    secs: 14
    nsecs: 752984383
  -
    secs: 6
    nsecs: 645550864
  -
    secs: 5
    nsecs: 404491675
  -
    secs: 10
    nsecs: 683979894
  -
    secs: 5
    nsecs: 736004001
  -
    secs: 9
    nsecs:  70277921
  -
    secs: 13
    nsecs:  68494686
  -
    secs: 15
    nsecs: 503896667
  -
    secs: 18
    nsecs: 645744664
  -
    secs: 8
    nsecs: 586347435
  -
    secs: 5
    nsecs: 330158537
  -
    secs: 21
    nsecs: 447085278
  -
    secs: 8
    nsecs: 933926716
  -
    secs: 8
    nsecs: 644765977
  -
    secs: 12
    nsecs: 803880336
  -
    secs: 6
    nsecs: 635527182
  -
    secs: 18
    nsecs: 961907940
  -
    secs: 4
    nsecs:  33603913
  -
    secs: 8
    nsecs: 421999256
  -
    secs: 14
    nsecs: 679049479
  -
    secs: 7
    nsecs: 761170794
  -
    secs: 16
    nsecs: 298927253
  -
    secs: 11
    nsecs:  15397177
  -
    secs: 15
    nsecs: 882553451
  -
    secs: 76
    nsecs:  73627086
  -
    secs: 47
    nsecs: 301196065
  -
    secs: 26
    nsecs: 738095616
  -
    secs: 27
    nsecs:  49099631
  -
    secs: 77
    nsecs: 528074744
  -
    secs: 44
    nsecs: 227153643
  -
    secs: 26
    nsecs: 740244096
  -
    secs: 44
    nsecs: 227153643
  -
    secs: 98
    nsecs: 371537711
  -
    secs: 26
    nsecs: 740244096
  -
    secs: 38
    nsecs: 962389985
  -
    secs: 46
    nsecs: 963520168
  -
    secs: 47
    nsecs: 301196065
  -
    secs: 53
    nsecs: 220975263
  -
    secs: 90
    nsecs: 950038429
  -
    secs: 13
    nsecs: 193542375
  -
    secs: 53
    nsecs: 220975263
  -
    secs: 27
    nsecs:  49099631
  -
    secs: 103
    nsecs: 176714512
  -
    secs: 41
    nsecs: 136769714
  -
    secs: 77
    nsecs: 528074744
  -
    secs: 41
    nsecs: 136769714
  -
    secs: 103
    nsecs: 176714512
  -
    secs: 13
    nsecs: 193542375
  -
    secs: 46
    nsecs: 963520168
  -
    secs: 27
    nsecs: 192453244
  -
    secs: 90
    nsecs: 950038429
  -
    secs: 38
    nsecs: 962389985
  -
    secs: 98
    nsecs: 371537711
  -
    secs: 27
    nsecs: 192453244
  -
    secs: 76
    nsecs:  73627086
```
